services:
  db:
    build: ./infra/db
    environment:
      POSTGRES_USER: sana
      POSTGRES_PASSWORD: sana
      POSTGRES_DB: sana_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
