"""add_alert_rules_and_events

Revision ID: 19cb35729da4
Revises: eb1658a8840c
Create Date: 2026-05-04 19:54:41.363354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cb35729da4'
down_revision: Union[str, Sequence[str], None] = 'eb1658a8840c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('observations_phenomenon_time_idx'), table_name='observations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('observations_phenomenon_time_idx'), 'observations', [sa.literal_column('phenomenon_time DESC')], unique=False)
    # ### end Alembic commands ###
