"""drop_sensor_model_properties

Revision ID: 7b800efb4eb6
Revises: 23445581726d
Create Date: 2026-04-18 22:38:31.729226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b800efb4eb6'
down_revision: Union[str, Sequence[str], None] = '23445581726d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_model_properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_model_properties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('observed_property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['observed_property_id'], ['observed_properties.id'], name=op.f('sensor_model_properties_observed_property_id_fkey')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('sensor_model_properties_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_model_properties_pkey')),
    sa.UniqueConstraint('model', 'observed_property_id', name=op.f('uq_sensor_model_props_model_property'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
