"""add_alert_rules_and_events

Revision ID: 8b40024ee49f
Revises: 19cb35729da4
Create Date: 2026-05-04 20:35:50.813604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b40024ee49f'
down_revision: Union[str, Sequence[str], None] = '19cb35729da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric', sa.Enum('THRESHOLD', 'SENSOR_OFFLINE', 'BATTERY_LOW', name='alert_metric'), nullable=False),
    sa.Column('operator', sa.Enum('GT', 'LT', 'GTE', 'LTE', name='alert_operator'), nullable=True),
    sa.Column('threshold', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(metric = 'THRESHOLD' AND operator IS NOT NULL AND threshold IS NOT NULL) OR (metric != 'THRESHOLD' AND operator IS NULL AND threshold IS NULL)", name='chk_threshold_fields'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_rules_unit', 'alert_rules', ['unit_id'], unique=False, postgresql_where='unit_id IS NOT NULL')
    op.create_index('idx_alert_rules_workspace', 'alert_rules', ['workspace_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center_lat', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('center_lon', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('radius_m', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_events_rule', 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index('idx_alert_events_triggered', 'alert_events', ['triggered_at'], unique=False, postgresql_ops={'triggered_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alert_events_triggered', table_name='alert_events', postgresql_ops={'triggered_at': 'DESC'})
    op.drop_index('idx_alert_events_rule', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('zones')
    op.drop_index('idx_alert_rules_workspace', table_name='alert_rules')
    op.drop_index('idx_alert_rules_unit', table_name='alert_rules', postgresql_where='unit_id IS NOT NULL')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
