"""add device config columns to sensors

Revision ID: 9b30c8714442
Revises: 019da785ee0c
Create Date: 2026-04-21 23:08:08.779116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b30c8714442'
down_revision: Union[str, Sequence[str], None] = '019da785ee0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sensors', sa.Column('sampling_interval_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False))
    op.add_column('sensors', sa.Column('transmission_interval_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'transmission_interval_seconds')
    op.drop_column('sensors', 'sampling_interval_seconds')
    op.drop_column('sensors', 'deactivated_at')
    # ### end Alembic commands ###
