"""drop_processing_levels_remove_from_datastreams

Revision ID: da7a89696de4
Revises: fd021faedf8d
Create Date: 2026-04-16 22:54:32.968406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7a89696de4'
down_revision: Union[str, Sequence[str], None] = 'fd021faedf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_datastreams_sensor_property_unit_level'), 'datastreams', type_='unique')
    op.drop_constraint(op.f('datastreams_processing_level_id_fkey'), 'datastreams', type_='foreignkey')
    op.drop_column('datastreams', 'processing_level_id')
    op.create_unique_constraint('uq_datastreams_sensor_property_unit', 'datastreams', ['sensor_id', 'observed_property_id', 'unit_id'])
    op.drop_table('processing_levels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datastreams', sa.Column('processing_level_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('datastreams_processing_level_id_fkey'), 'datastreams', 'processing_levels', ['processing_level_id'], ['id'])
    op.drop_constraint('uq_datastreams_sensor_property_unit', 'datastreams', type_='unique')
    op.create_unique_constraint(op.f('uq_datastreams_sensor_property_unit_level'), 'datastreams', ['sensor_id', 'observed_property_id', 'unit_id', 'processing_level_id'], postgresql_nulls_not_distinct=False)
    op.create_table('processing_levels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_levels_pkey')),
    sa.UniqueConstraint('code', name=op.f('processing_levels_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
