"""add qualifier to observations drop observation_qualifiers

Revision ID: fd021faedf8d
Revises: 0fbc92252007
Create Date: 2026-04-15 20:15:46.452812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd021faedf8d'
down_revision: Union[str, Sequence[str], None] = '0fbc92252007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_qualifiers')
    op.add_column('observations', sa.Column('qualifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'qualifier')
    op.create_table('observation_qualifiers',
    sa.Column('observation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phenomenon_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('qualifier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['qualifier_id'], ['result_qualifiers.id'], name=op.f('observation_qualifiers_qualifier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id', 'phenomenon_time', 'qualifier_id', name=op.f('observation_qualifiers_pkey'))
    )
    # ### end Alembic commands ###
